[platformio]
default_envs = esp32dev
src_dir = main
build_dir = .pio/build

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/set_component_cache.py
build_flags =
  -DCHIP_HAVE_CONFIG_H
  '-DCHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME="devprbtt"'
  '-DCHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME="esp32-ir-server"'
lib_ldf_mode = chain+
